"""add ohlcv_data

Revision ID: 290d3db05ab6
Revises: 6f2c5d38d8fe
Create Date: 2026-02-24 16:31:56.852747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290d3db05ab6'
down_revision = '6f2c5d38d8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'timeframe', 'timestamp', name='uq_ohlcv')
    )
    with op.batch_alter_table('ohlcv_data', schema=None) as batch_op:
        batch_op.create_index('idx_ohlcv_query', ['product_code', 'timeframe', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ohlcv_data_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ohlcv_data_timeframe'), ['timeframe'], unique=False)
        batch_op.create_index(batch_op.f('ix_ohlcv_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ohlcv_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ohlcv_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ohlcv_data_timeframe'))
        batch_op.drop_index(batch_op.f('ix_ohlcv_data_product_code'))
        batch_op.drop_index('idx_ohlcv_query')

    op.drop_table('ohlcv_data')
    # ### end Alembic commands ###
