"""Increase contract_month length

Revision ID: 6f2c5d38d8fe
Revises: e8d2e8d2e8d2
Create Date: 2026-02-20 22:40:25.313124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2c5d38d8fe'
down_revision = 'e8d2e8d2e8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.alter_column('contract_month',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.alter_column('contract_month',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
