"""Initial migration

Revision ID: ba427bf17956
Revises: 
Create Date: 2026-01-18 02:27:40.607569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba427bf17956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_net_worth', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('equity_us', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('equity_tw', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('equity_futures', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('usd_twd_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holdings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_instrument')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_holdings')
    op.drop_table('instruments')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
