"""add tick data table

Revision ID: e8d2e8d2e8d2
Revises: c7204c5e891c
Create Date: 2026-02-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d2e8d2e8d2'
down_revision = 'c7204c5e891c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tick_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('contract_month', sa.String(length=10), nullable=False),
    sa.Column('trade_time', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tick_data_contract_month'), ['contract_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_tick_data_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tick_data_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index('idx_product_contract_date', ['product_code', 'contract_month', 'trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.drop_index('idx_product_contract_date')
        batch_op.drop_index(batch_op.f('ix_tick_data_trade_date'))
        batch_op.drop_index(batch_op.f('ix_tick_data_product_code'))
        batch_op.drop_index(batch_op.f('ix_tick_data_contract_month'))

    op.drop_table('tick_data')
    # ### end Alembic commands ###
